### ISSUE TITLE
docker port_mapping option doesn't seem to work right...

### ISSUE THREAD

**Issue by Gnuxie** [matrix-org/mx-tester#19]
If you have the following in mx-tester.yml

```
docker:
  hostname: synapse
  port_mapping:
    - host: 8081
      guest: 8008
```

Then the host port seems to be ignored and mx-tester still uses `9999`.
